#!/bin/bash KDE Setup Program
#Copyright (c) 2026 By Marvin.W

set -eu

apt update
apt install -y --no-install-recommends kde-plasma-desktop sddm systemsettings kwin-addons kwin-x11 librsvg2-common plymouth-label \
kde-config-sddm polkit-kde-agent-1 powerdevil kde-config-screenlocker kde-config-gtk-style kde-config-gtk-style-preview \
 kio-extras kio-fuse breeze-gtk-theme sddm-theme-debian-breeze kde-config-plymouth plymouth-theme-breeze \
konsole kio-admin plasma-workspace kwalletmanager kcalc kfind gwenview plasma-nm sweeper plasma-pa kwrite \
fonts-arphic-ukai fonts-arphic-uming \
xrdp xorgxrdp
systemctl enable --now xrdp

# Fix KDE Network with Wrong Ethernet Interface Inspect:
sed -i /ens18/d /etc/network/interfaces
sed -i s/managed=false/manged=true/ /etc/NetworkManager/NetworkManager.conf

# Add Rules for Remote Desktop Control to Evade Permission Validation:
usermod -aG netdev marvin
cat <<-EOF >> /etc/polkit-1/rules.d/49-remote-networkmanager.rules
polkit.addRule(function(action, subject) {
    const allowed = [
        "org.freedesktop.NetworkManager.network-control",
        "org.freedesktop.NetworkManager.settings.modify.system",
        "org.freedesktop.NetworkManager.checkpoint-rollback",
        "org.freedesktop.NetworkManager.enable-disable-network",
        "org.freedesktop.NetworkManager.enable-disable-statistics",
        "org.freedesktop.NetworkManager.enable-disable-wifi",
        "org.freedesktop.NetworkManager.enable-disable-wwan",
        "org.freedesktop.NetworkManager.settings.modify.global-dns",
        "org.freedesktop.NetworkManager.settings.modify.hostname",
        "org.freedesktop.NetworkManager.settings.modify.own",
        "org.freedesktop.NetworkManager.settings.modify.system",
        "org.freedesktop.NetworkManager.sleep-wake",
        "org.freedesktop.NetworkManager.vpn",
        "org.freedesktop.NetworkManager.sleep-wake",
        "org.freedesktop.NetworkManager.wifi.scan"
    ];

    if (allowed.indexOf(action.id) >= 0 && subject.isInGroup("netdev")) {
        return polkit.Result.YES;
    }
});
EOF

cat <<-EOF >>  /etc/polkit-1/rules.d/10-shutdown-reboot.rules
polkit.addRule(function(action, subject) {
    if (
        (action.id == "org.freedesktop.login1.reboot" ||
         action.id == "org.freedesktop.login1.reboot-multiple-sessions" ||
         action.id == "org.freedesktop.login1.reboot-ignore-inhibit" ||
         action.id == "org.freedesktop.login1.power-off" ||
         action.id == "org.freedesktop.login1.power-off-multiple-sessions" ||
         action.id == "org.freedesktop.login1.power-off-ignore-inhibit") &&
        (subject.user == "marvin" || subject.isInGroup("sudo"))
    ) {
        return polkit.Result.YES;
    }
});
EOF

# Disable Screen Lock Automatically:
sudo -u marvin kwriteconfig6 --file kscreenlockerrc --group Daemon --key Timeout 0
sudo -u marvin kwriteconfig6 --file kscreenlockerrc --group Daemon --key RequirePassword false

exit 0
