#!/bin/bash Debian Initiation Program
#Copyright (c) 2026 By Marvin.W

set -eu

apt install -y --no-install-recommends sudo kde-plasma-desktop sddm kwin-addons kwin-x11 xserver-xorg xrdp xorgxrdp \
librsvg2-common plymouth-label \
kde-baseapp kio-admin polkit-kde-agent-1 kwalletmanager korganizer kate kcalc gwenview plasma-nm sweeper plasma-pa \
fonts-arphic-ukai fonts-arphic-uming
systemctl enable --now xrdp
exit 0
